name: efipay
description: A dart library for integration with payment services provided by Efi.
version: 1.0.6
homepage: https://github.com/efipay/sdk-dart-apis-efi

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dio: ^5.0.0
  encrypt: ^5.0.1
  pointycastle: ^3.6.2
  json_annotation: ^4.8.0
  http: ^0.13.5
  crypto: ^3.0.2

dev_dependencies:
  test: ^1.17.1
  build_runner: ^2.3.0
  json_serializable: ^6.5.0
